version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - 2181:2181
      - 2581:2581
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 1
      KAFKA_JMX_OPTS: '-Djava.rmi.server.hostname=zookeeper -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=2581 -Dcom.sun.management.jmxremote.port=2581 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'

  kafka:
    image: debezium/kafka:1.0
    ports:
      - 9092:9092
      - 9592:9592
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      ADVERTISED_HOST_NAME: 'kafka'
      BROKER_ID: 0
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      JMX_OPTS: '-Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9592 -Dcom.sun.management.jmxremote.port=9592 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'

  postgres:
    build:
      context: ./postgres
    ports:
      - 5432:5432

  connector:
    build:
      context: ./mybug
      dockerfile: ./bug-connector/Dockerfile
    ports:
      - 8083:8083
      - 6532:6532
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: connect_configs
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_TOPIC: connect_offsets
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_TOPIC: connect_status
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      REST_ADVERTISED_HOST_NAME: connector
      PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
      JMX_OPTS: '-Djava.rmi.server.hostname=connector -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=6532 -Dcom.sun.management.jmxremote.port=6532 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'

  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.0
    ports:
      - 8081:8081
      - 8581:8581
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry:8081
      ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: BACKWARD_TRANSITIVE
      SCHEMA_REGISTRY_JMX_OPTS: '-Djava.rmi.server.hostname=schemaregistry -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=8581 -Dcom.sun.management.jmxremote.port=8581 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'

  setup:
    build:
      context: ./setup
    command: sh -c "python3 -u /usr/local/bin/setup.py"

networks:
  default:
    external:
      name: local
